// Butter
var LIGHT_BUTTER 	= "#FCE94F";
var MED_BUTTER		= "#EDD400";
var DARK_BUTTER		= "#C4A000";
var BUTTER 			= [LIGHT_BUTTER, MED_BUTTER, DARK_BUTTER];

var LIGHT_ORANGE	= "#FCAF3E";
var MED_ORANGE		= "#F57900";
var DARK_ORANGE		= "#CE5C00";
var ORANGE 			= [LIGHT_ORANGE, MED_ORANGE, DARK_ORANGE];

var LIGHT_CHOCOLATE	= "#E9B96E";
var MED_CHOCOLATE	= "#C17D11";
var DARK_CHOCOLATE	= "#8F5902";
var CHOCOLATE 		= [LIGHT_CHOCOLATE, MED_CHOCOLATE, DARK_CHOCOLATE]; 

var LIGHT_CHAMELEON	= "#8AE234";
var MED_CHAMELEON	= "#73D216";
var DARK_CHAMELEON	= "#4E9A06";
var CHAMELEON 		= [LIGHT_CHAMELEON, MED_CHAMELEON, DARK_CHAMELEON];

var LIGHT_SKY_BLUE	= "#729FCF";
var MED_SKY_BLUE	= "#3465A4";
var DARK_SKY_BLUE 	= "#204A87";
var SKY_BLUE 		= [LIGHT_SKY_BLUE, MED_SKY_BLUE, DARK_SKY_BLUE];

var LIGHT_PLUM		= "#AD7FA8";
var MED_PLUM		= "#75507B";
var DARK_PLUM		= "#5C3566";
var PLUM 			= [LIGHT_PLUM, MED_PLUM, DARK_PLUM];

var LIGHT_RED		= "#EF2929";
var MED_RED			= "#CC0000";
var DARK_RED		= "#A40000";
var RED 			= [LIGHT_RED, MED_RED, DARK_RED];

var LIGHT_GREY		= "#EEEEEC";
var MED_GREY		= "#D3D7CF";
var DARK_GREY		= "#BABDB6";
var GREY 			= [LIGHT_GREY, MED_GREY, DARK_GREY];

var LIGHT_ALUMINUM	= "#888A85";
var MED_ALUMINUM	= "#555753";
var DARK_ALUMINUM	= "#2E3436";
var ALUMINUM 		= [LIGHT_ALUMINUM, MED_ALUMINUM, DARK_ALUMINUM];